site_name: 概率论与数理统计
site_url: https://eanyang7.github.io/Probability-and-Statistics
site_description: "《概率论与数理统计》陈希孺，中国科学技术大学出版社"
repo_url: https://github.com/EanYang7/Probability-and-Statistics
repo_name: EanYang7/Probability-and-Statistics

theme:
  language: zh 
  name: material
  custom_dir: overrides
  logo: cover.jpg
  favicon: cover.jpg
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.follow
    - content.action.edit
    - content.action.view

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换为暗黑模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换为浅色模式
  # 设置右上角图标
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

markdown_extensions:
  - toc:
      permalink: ⚓︎
  
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - git-revision-date-localized:
    enable_creation_date: true
 - search
 


edit_uri: "tree/main/docs/"

nav:
  - 首页: 
    - 'index.md'

  - 课程: 
    - 章节: 
      - 第1章 事件的概率:
        - 1.1 概率是什么: 'courses/1-Probability-of-events/1-What-is-the-probability.md'
        - 1.2 古典概率计算: 'courses/1-Probability-of-events/2-Classical-Probability-Calculation.md'
        - 1.3 事件的运算、条件概率与独立性: 'courses/1-Probability-of-events/3-Operation-Conditional-probability-and-independence-of-events.md'
        - 习题: 'courses/1-Probability-of-events/exercises.md'
        - 答案: 'courses/1-Probability-of-events/answers.md'
      - 第2章 随机变量及概率分布: 
        - 2.1 一维随机变量: 'courses/2-Random-Variables-and-Probability-Distribution/1-One-dimensional-random-variable.md'
        - 2.2 多维随机变量（随机向量）: 'courses/2-Random-Variables-and-Probability-Distribution/2-Multidimensional-random-variables-random-vectors.md'
        - 2.3 条件概率分布与随机变量的独立性: 'courses/2-Random-Variables-and-Probability-Distribution/3-Independence-of-Conditional-probability-distribution-and-random-variable.md'
        - 2.4 随机变量的函数的概率分布: 'courses/2-Random-Variables-and-Probability-Distribution/4-Probability-Distribution-of-Functions-of-Random-Variables.md'
        - 附录: 'courses/2-Random-Variables-and-Probability-Distribution/appendix.md'
        - 习题: 'courses/2-Random-Variables-and-Probability-Distribution/exercises.md'
        - 答案: 'courses/2-Random-Variables-and-Probability-Distribution/answers.md'
      - 第3章 随机变量的数字特征: 
        - 3.1 数学期望（均值）与中位数: 'courses/3-Numerical-Characteristics-of-Random-Variables/1-Mathematica-Expectations-Mean-and-Median.md'
        - 3.2 方差与矩: 'courses/3-Numerical-Characteristics-of-Random-Variables/2-Variance-and-Moment.md'
        - 3.3 协方差与相关系数: 'courses/3-Numerical-Characteristics-of-Random-Variables/3-Covariance-and-correlation-coefficient.md'
        - 3.4 大数定理和中心极限定理: 'courses/3-Numerical-Characteristics-of-Random-Variables/4-Theorem-of-Large-Numbers.md'
        - 习题: 'courses/3-Numerical-Characteristics-of-Random-Variables/exercises.md'
        - 答案: 'courses/3-Numerical-Characteristics-of-Random-Variables/answers.md'
      - 第4章 参数估计: 
        - 4.1 数理统计学的基本概念: 'courses/4-Parameter-Estimates/1-Basic-concepts-of-Mathematical-statistics.md'
        - 4.2 矩估计、极大似然估计和贝叶斯估计: 'courses/4-Parameter-Estimates/2-Moment-estimation-maximum-likelihood-estimation-and-Bayesian-estimation.md'
        - 4.3 点估计的优良性准则: 'courses/4-Parameter-Estimates/3-Excellence-criterion-of-Point-estimation.md'
        - 4.4 区间估计: 'courses/4-Parameter-Estimates/4-Interval-estimation.md'
        - 习题: 'courses/4-Parameter-Estimates/exercises.md'
        - 答案: 'courses/4-Parameter-Estimates/answers.md'
      - 第5章 假设检验: 
        - 5.1 问题提法和基本概念: 'courses/5-Hypothesis-Testing/1-Problem-formulation-and-basic-concepts.md'
        - 5.2 重要参数检验: 'courses/5-Hypothesis-Testing/2-Important-parameter-inspection.md'
        - 5.3 拟合优度检验: 'courses/5-Hypothesis-Testing/3-goodness-of-fit-test.md'
        - 附录: 'courses/5-Hypothesis-Testing/appendix.md'
        - 习题: 'courses/5-Hypothesis-Testing/exercises.md'
        - 答案: 'courses/5-Hypothesis-Testing/answers.md'
      - 第6章 回归、相关与方差分析: 
        - 6.1 回归分析基本概念: 'courses/6-Regression-Correlation-and-Analysis-of-Variance/1-Basic-concepts-of-regression-analysis.md'
        - 6.2 一元线性回归: 'courses/6-Regression-Correlation-and-Analysis-of-Variance/2-Univariate-linear-regression.md'
        - 6.3 多元线性回归: 'courses/6-Regression-Correlation-and-Analysis-of-Variance/3-Multiple-linear-regression.md'
        - 6.4 相关分析: 'courses/6-Regression-Correlation-and-Analysis-of-Variance/4-Correlation-analysis.md'
        - 6.5 方差分析: 'courses/6-Regression-Correlation-and-Analysis-of-Variance/5-Analysis-of-variance.md'
        - 附录: 'courses/6-Regression-Correlation-and-Analysis-of-Variance/appendix.md'
        - 习题: 'courses/6-Regression-Correlation-and-Analysis-of-Variance/exercises.md'
        - 答案: 'courses/6-Regression-Correlation-and-Analysis-of-Variance/answers.md'
      - 附表: 'courses/appendix.md'


  - PDF: '《概率论与数理统计》陈希孺，中国科学技术大学出版社.pdf'


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EanYang7/cs231n
  # generator: false 
  analytics:
    provider: google
    property: G-GEDRLMN4ML
    feedback:
      title: 对当前页面有任何疑问吗？
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            感谢您的反馈！
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            感谢您的反馈！请点击这里<a href="https://github.com/EanYang7/Probability-and-Statistics/issues" target="_blank" rel="noopener">这里</a>提供问题反馈.


extra_css:
- stylesheets/extra.css