site_name: 概率论与数理统计
site_url: https://eanyang7.github.io/Probability-and-Statistics
site_description: "《概率论与数理统计》陈希孺，中国科学技术大学出版社"
repo_url: https://github.com/EanYang7/Probability-and-Statistics
repo_name: EanYang7/Probability-and-Statistics

theme:
  language: zh 
  name: material
  logo: 封面.jpg
  favicon: 封面.jpg
  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - toc.follow
    - content.action.edit
    - content.action.view

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换为暗黑模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换为浅色模式
  # 设置右上角图标
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

markdown_extensions:
  - toc:
      permalink: ⚓︎
  
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - git-revision-date-localized:
    enable_creation_date: true
 - search


edit_uri: "edit/dev/docs/"

nav:
  - 首页: 
    - 'index.md'

  - 课程: 
    - 章节:
      - 第1章 事件的概率: 
        - 第一单元pdf: '课程/01-第1章-事件的概率/pdf.md'
        - 1.1 概率是什么: '课程/01-第1章-事件的概率/01-概率是什么.md'
        - 1.2 古典概率计算: '课程/01-第1章-事件的概率/02-古典概率计算.md'
        - 1.3 事件的运算、条件概率与独立性: '课程/01-第1章-事件的概率/03-事件的运算、条件概率与独立性.md'
        - 习题: '附录、习题与答案\第1单元习题.md'
      - 第2章 随机变量及概率分布: 
        - 2.1 一维随机变量: '课程/02-第2章-随机变量及概率分布/01-一维随机变量.md'
        - 2.2 多维随机变量（随机向量）: '课程/02-第2章-随机变量及概率分布/02-多维随机变量（随机向量）.md'
        - 2.3 条件概率分布与随机变量的独立性: '课程/02-第2章-随机变量及概率分布/03-条件概率分布与随机变量的独立性.md'
        - 2.4 随机变量的函数的概率分布: '课程/02-第2章-随机变量及概率分布/04-随机变量的函数的概率分布.md'
        - 附录: '附录、习题与答案\第2单元附录.md'
        - 习题: '附录、习题与答案\第2单元习题.md'
      - 第3章 随机变量的数字特征: 
        - 3.1 数学期望（均值）与中位数: '课程/03-第3章-随机变量的数字特征/01-数学期望（均值）与中位数.md'
        - 3.2 方差与矩: '课程/03-第3章-随机变量的数字特征/02-方差与矩.md'
        - 3.3 协方差与相关系数: '课程/03-第3章-随机变量的数字特征/03-协方差与相关系数.md'
        - 3.4 大数定理和中心极限定理: '课程/03-第3章-随机变量的数字特征/04-大数定理.md'
        - 习题: '附录、习题与答案\第3单元习题.md'
      - 第4章 参数估计: 
        - 4.1 数理统计学的基本概念: '课程/04-第4章-参数估计/01-数理统计学的基本概念.md'
        - 4.2 矩估计、极大似然估计和贝叶斯估计: '课程/04-第4章-参数估计/02-矩估计、极大似然估计和贝叶斯估计.md'
        - 4.3 点估计的优良性准则: '课程/04-第4章-参数估计/03-点估计的优良性准则.md'
        - 4.4 区间估计: '课程/04-第4章-参数估计/04-区间估计.md'
        - 习题: '附录、习题与答案\第4单元习题.md'
      - 第5章 假设检验: 
        - 5.1 问题提法和基本概念: '课程/05-第5章-假设检验/01-问题提法和基本概念.md'
        - 5.2 重要参数检验: '课程/05-第5章-假设检验/02-重要参数检验.md'
        - 5.3 拟合优度检验: '课程/05-第5章-假设检验/03-拟合优度检验.md'
        - 附录: '附录、习题与答案\第5单元附录.md'
        - 习题: '附录、习题与答案\第5单元习题.md'
      - 第6章 回归、相关与方差分析: 
        - 6.1 回归分析基本概念: '课程/06-第6章-回归、相关与方差分析/01-回归分析基本概念.md'
        - 6.2 一元线性回归: '课程/06-第6章-回归、相关与方差分析/02-一元线性回归'
        - 6.3 多元线性回归: '课程/06-第6章-回归、相关与方差分析/03-多元线性回归'
        - 6.4 相关分析: '课程/06-第6章-回归、相关与方差分析/04-相关分析'
        - 6.5 方差分析: '课程/06-第6章-回归、相关与方差分析/05-方差分析'
        - 附录: '附录、习题与答案\第6单元附录.md'
        - 习题: '附录、习题与答案\第6单元习题.md'
  - 作业: 
    - " ":
      - 第1单元:
        - 习题: '附录、习题与答案\第1单元习题.md'
        - 答案: '附录、习题与答案\第1单元答案.md'
      - 第2单元:
        - 习题: '附录、习题与答案\第2单元习题.md'
        - 答案: '附录、习题与答案\第2单元答案.md'   
      - 第3单元:
        - 习题: '附录、习题与答案\第3单元习题.md'
        - 答案: '附录、习题与答案\第3单元答案.md'   
      - 第4单元:
        - 习题: '附录、习题与答案\第4单元习题.md'
        - 答案: '附录、习题与答案\第4单元答案.md'   
      - 第5单元:
        - 习题: '附录、习题与答案\第5单元习题.md'
        - 答案: '附录、习题与答案\第5单元答案.md'   
      - 第6单元:
        - 习题: '附录、习题与答案\第6单元习题.md'
        - 答案: '附录、习题与答案\第6单元答案.md'   

  - 附表: '附录、习题与答案\附表.md'


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EanYang7/cs231n
  generator: false 

extra_css:
- stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js